app:
  paths:
    configurations:
      configuration: app/config
      router: app/router
    resources:
      template:
        - app/resources/template
    source-code:
      controller:
        - app/src/Controller
      api:
        - app/src/Api
      template-engine:
        - app/src/TemplateEngine
